name: Lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: ^1.18.0-beta1
        id: go
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          # * Build cache (Windows)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: '1.18.0-beta1'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "--timeout=15m --enable-all --exclude-use-default=false -D wsl -D godox -D promlinter -D tagliatelle"
          level: warning
          reporter: github-check